const mongoose=require("mongoose");
// const commentSchema=require("./Comment");
const blogSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
        unique:true,
        primaryKey:true
    },
    image:{
        type:String,
        required:true
    },
    author:{
        type:String,
        required:true
    },
    content:{
        type:String,
        required:true
    },
    createdAt:{
        type:Date,
        default:Date.now()
    },
    updatedAt:{
        type:Date,
        default:Date.now()
    },
    likes:{
        type:Number,
        required:true,
        default:0
    },
    createdAt:{
        type:Date,
        default:Date.now()
    },
    updatedAt:{
        type:Date,
        default:Date.now()
    },
})
module.exports=mongoose.model("Blog",blogSchema);