const express=require('express');
const router=express.Router();
const loginController=require('../controllers/loginController');
router.get("/register",loginController.registerUserPage);
router.post("/register",loginController.registerUser);
// router.post("/login",loginController.loginUser);
router.get("/:id",loginController.getUserById);
router.get('/',loginController.getUsers);
router.put("/:id",loginController.updateUser);
router.delete("/:id",loginController.deleteUser);
module.exports=router;